/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UQidRouteImport } from './routes/u.$qid'
import { Route as PPidRouteImport } from './routes/p.$pid'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedProfileRouteRouteImport } from './routes/_protected/profile/route'
import { Route as ProtectedPostsRouteRouteImport } from './routes/_protected/posts/route'
import { Route as ProtectedChatsRouteRouteImport } from './routes/_protected/chats/route'
import { Route as ProtectedChatsIndexRouteImport } from './routes/_protected/chats/index'
import { Route as ProtectedProfileSettingsRouteImport } from './routes/_protected/profile/settings'
import { Route as ProtectedProfileHomeRouteImport } from './routes/_protected/profile/home'
import { Route as ProtectedProfileCreateRouteImport } from './routes/_protected/profile/create'
import { Route as ProtectedPostsHomeRouteImport } from './routes/_protected/posts/home'
import { Route as ProtectedChatsHomeRouteImport } from './routes/_protected/chats/home'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UQidRoute = UQidRouteImport.update({
  id: '/u/$qid',
  path: '/u/$qid',
  getParentRoute: () => rootRouteImport,
} as any)
const PPidRoute = PPidRouteImport.update({
  id: '/p/$pid',
  path: '/p/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRouteRoute = ProtectedProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPostsRouteRoute = ProtectedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedChatsRouteRoute = ProtectedChatsRouteRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedChatsIndexRoute = ProtectedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedChatsRouteRoute,
} as any)
const ProtectedProfileSettingsRoute =
  ProtectedProfileSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedProfileRouteRoute,
  } as any)
const ProtectedProfileHomeRoute = ProtectedProfileHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedProfileRouteRoute,
} as any)
const ProtectedProfileCreateRoute = ProtectedProfileCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProtectedProfileRouteRoute,
} as any)
const ProtectedPostsHomeRoute = ProtectedPostsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedPostsRouteRoute,
} as any)
const ProtectedChatsHomeRoute = ProtectedChatsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedChatsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ProtectedChatsRouteRouteWithChildren
  '/posts': typeof ProtectedPostsRouteRouteWithChildren
  '/profile': typeof ProtectedProfileRouteRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/p/$pid': typeof PPidRoute
  '/u/$qid': typeof UQidRoute
  '/chats/home': typeof ProtectedChatsHomeRoute
  '/posts/home': typeof ProtectedPostsHomeRoute
  '/profile/create': typeof ProtectedProfileCreateRoute
  '/profile/home': typeof ProtectedProfileHomeRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/chats/': typeof ProtectedChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof ProtectedPostsRouteRouteWithChildren
  '/profile': typeof ProtectedProfileRouteRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/p/$pid': typeof PPidRoute
  '/u/$qid': typeof UQidRoute
  '/chats/home': typeof ProtectedChatsHomeRoute
  '/posts/home': typeof ProtectedPostsHomeRoute
  '/profile/create': typeof ProtectedProfileCreateRoute
  '/profile/home': typeof ProtectedProfileHomeRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/chats': typeof ProtectedChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/chats': typeof ProtectedChatsRouteRouteWithChildren
  '/_protected/posts': typeof ProtectedPostsRouteRouteWithChildren
  '/_protected/profile': typeof ProtectedProfileRouteRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/p/$pid': typeof PPidRoute
  '/u/$qid': typeof UQidRoute
  '/_protected/chats/home': typeof ProtectedChatsHomeRoute
  '/_protected/posts/home': typeof ProtectedPostsHomeRoute
  '/_protected/profile/create': typeof ProtectedProfileCreateRoute
  '/_protected/profile/home': typeof ProtectedProfileHomeRoute
  '/_protected/profile/settings': typeof ProtectedProfileSettingsRoute
  '/_protected/chats/': typeof ProtectedChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/posts'
    | '/profile'
    | '/home'
    | '/p/$pid'
    | '/u/$qid'
    | '/chats/home'
    | '/posts/home'
    | '/profile/create'
    | '/profile/home'
    | '/profile/settings'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts'
    | '/profile'
    | '/home'
    | '/p/$pid'
    | '/u/$qid'
    | '/chats/home'
    | '/posts/home'
    | '/profile/create'
    | '/profile/home'
    | '/profile/settings'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/chats'
    | '/_protected/posts'
    | '/_protected/profile'
    | '/_protected/home'
    | '/p/$pid'
    | '/u/$qid'
    | '/_protected/chats/home'
    | '/_protected/posts/home'
    | '/_protected/profile/create'
    | '/_protected/profile/home'
    | '/_protected/profile/settings'
    | '/_protected/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PPidRoute: typeof PPidRoute
  UQidRoute: typeof UQidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$qid': {
      id: '/u/$qid'
      path: '/u/$qid'
      fullPath: '/u/$qid'
      preLoaderRoute: typeof UQidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pid': {
      id: '/p/$pid'
      path: '/p/$pid'
      fullPath: '/p/$pid'
      preLoaderRoute: typeof PPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/posts': {
      id: '/_protected/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ProtectedPostsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/chats': {
      id: '/_protected/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ProtectedChatsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/chats/': {
      id: '/_protected/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ProtectedChatsIndexRouteImport
      parentRoute: typeof ProtectedChatsRouteRoute
    }
    '/_protected/profile/settings': {
      id: '/_protected/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProtectedProfileSettingsRouteImport
      parentRoute: typeof ProtectedProfileRouteRoute
    }
    '/_protected/profile/home': {
      id: '/_protected/profile/home'
      path: '/home'
      fullPath: '/profile/home'
      preLoaderRoute: typeof ProtectedProfileHomeRouteImport
      parentRoute: typeof ProtectedProfileRouteRoute
    }
    '/_protected/profile/create': {
      id: '/_protected/profile/create'
      path: '/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProtectedProfileCreateRouteImport
      parentRoute: typeof ProtectedProfileRouteRoute
    }
    '/_protected/posts/home': {
      id: '/_protected/posts/home'
      path: '/home'
      fullPath: '/posts/home'
      preLoaderRoute: typeof ProtectedPostsHomeRouteImport
      parentRoute: typeof ProtectedPostsRouteRoute
    }
    '/_protected/chats/home': {
      id: '/_protected/chats/home'
      path: '/home'
      fullPath: '/chats/home'
      preLoaderRoute: typeof ProtectedChatsHomeRouteImport
      parentRoute: typeof ProtectedChatsRouteRoute
    }
  }
}

interface ProtectedChatsRouteRouteChildren {
  ProtectedChatsHomeRoute: typeof ProtectedChatsHomeRoute
  ProtectedChatsIndexRoute: typeof ProtectedChatsIndexRoute
}

const ProtectedChatsRouteRouteChildren: ProtectedChatsRouteRouteChildren = {
  ProtectedChatsHomeRoute: ProtectedChatsHomeRoute,
  ProtectedChatsIndexRoute: ProtectedChatsIndexRoute,
}

const ProtectedChatsRouteRouteWithChildren =
  ProtectedChatsRouteRoute._addFileChildren(ProtectedChatsRouteRouteChildren)

interface ProtectedPostsRouteRouteChildren {
  ProtectedPostsHomeRoute: typeof ProtectedPostsHomeRoute
}

const ProtectedPostsRouteRouteChildren: ProtectedPostsRouteRouteChildren = {
  ProtectedPostsHomeRoute: ProtectedPostsHomeRoute,
}

const ProtectedPostsRouteRouteWithChildren =
  ProtectedPostsRouteRoute._addFileChildren(ProtectedPostsRouteRouteChildren)

interface ProtectedProfileRouteRouteChildren {
  ProtectedProfileCreateRoute: typeof ProtectedProfileCreateRoute
  ProtectedProfileHomeRoute: typeof ProtectedProfileHomeRoute
  ProtectedProfileSettingsRoute: typeof ProtectedProfileSettingsRoute
}

const ProtectedProfileRouteRouteChildren: ProtectedProfileRouteRouteChildren = {
  ProtectedProfileCreateRoute: ProtectedProfileCreateRoute,
  ProtectedProfileHomeRoute: ProtectedProfileHomeRoute,
  ProtectedProfileSettingsRoute: ProtectedProfileSettingsRoute,
}

const ProtectedProfileRouteRouteWithChildren =
  ProtectedProfileRouteRoute._addFileChildren(
    ProtectedProfileRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedChatsRouteRoute: typeof ProtectedChatsRouteRouteWithChildren
  ProtectedPostsRouteRoute: typeof ProtectedPostsRouteRouteWithChildren
  ProtectedProfileRouteRoute: typeof ProtectedProfileRouteRouteWithChildren
  ProtectedHomeRoute: typeof ProtectedHomeRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChatsRouteRoute: ProtectedChatsRouteRouteWithChildren,
  ProtectedPostsRouteRoute: ProtectedPostsRouteRouteWithChildren,
  ProtectedProfileRouteRoute: ProtectedProfileRouteRouteWithChildren,
  ProtectedHomeRoute: ProtectedHomeRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PPidRoute: PPidRoute,
  UQidRoute: UQidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
