/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPostsRouteImport } from './routes/_protected/posts'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedChatsRouteImport } from './routes/_protected/chats'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPostsRoute = ProtectedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedChatsRoute = ProtectedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/chats': typeof ProtectedChatsRoute
  '/home': typeof ProtectedHomeRoute
  '/posts': typeof ProtectedPostsRoute
  '/profile': typeof ProtectedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/chats': typeof ProtectedChatsRoute
  '/home': typeof ProtectedHomeRoute
  '/posts': typeof ProtectedPostsRoute
  '/profile': typeof ProtectedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_protected/chats': typeof ProtectedChatsRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/posts': typeof ProtectedPostsRoute
  '/_protected/profile': typeof ProtectedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signup' | '/chats' | '/home' | '/posts' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup' | '/chats' | '/home' | '/posts' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/signup'
    | '/_protected/chats'
    | '/_protected/home'
    | '/_protected/posts'
    | '/_protected/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/posts': {
      id: '/_protected/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ProtectedPostsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/chats': {
      id: '/_protected/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ProtectedChatsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedChatsRoute: typeof ProtectedChatsRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedPostsRoute: typeof ProtectedPostsRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedChatsRoute: ProtectedChatsRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedPostsRoute: ProtectedPostsRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
